## Python for beginners

In [1]:
print("Python is easy")

Python is easy


In [ ]:
# comments
# this is one

In [14]:
# data types

# five types are
# None object that contains no value
# Numeric int, float, complex
# Sequences str, bytes, bytearray, list, tuple, range
# Mapping for MapReduce

a = 10
f = 10.23
s = "You are the creator of your destiny"
d = 3+4j
e = 0B1010 # binary becomes int
g = 0XFF # hexadecimal becomes int
h = 0O33 # octadecimal
i = False

print(type(a))
print(type(f))
print(type(s))
print(type(d))
print(type(e))
print(type(g))
print(type(h))
print(type(i))

print(e)
print(g)
print(h)

# casting, convert types
print("int cast {}".format(int(f)))
print("bin cast {}".format(bin(10)))
print("hex cast {}".format(hex(10)))
print("oct cast {}".format(oct(10)))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'complex'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'bool'>
10
255
27
int cast 10
bin cast 0b1010
hex cast 0xa
oct cast 0o12


In [18]:
# identifiers
# case sensitive
id = 2
Id = 3
_id = 4
# two underscores indicate a special function
# __init__ 

In [19]:
# drivers license
firstName = "Adam"
lastName = "Smith"
age = "90"
ssn = "ajhd-adsf-sfdf-deee"
height = "6.2"
weight = "192"

print(firstName)
print(lastName)
print(age)
print(ssn)
print(height)
print(weight)

Adam
Smith
90
ajhd-adsf-sfdf-deee
6.2
192


In [21]:
# strings
s1 = "You are the creator of your destiny. "

# print
print(s1)

# multiply
print(s1 * 3)

# index
print(s1[2])
print(len(s1))
print(s1[0:3])
print(s1[0:])
print(s1[-4:-1])
print(s1[-4:])
print(s1[0:8:2])
print(s1[-15::1])
print(s1[-15::-1])

# strip 
s2 = "    creator of your destiny      "
print(s2.strip())
print(s2.lstrip())
print(s2.rstrip())

# find string in a string
print(s1.find("are", 0, len(s1)))
print(s2.find("are", 0, len(s1)))

# count
print(s2.count("t"))

You are the creator of your destiny. 
You are the creator of your destiny. You are the creator of your destiny. You are the creator of your destiny. 
u
37
You
You are the creator of your destiny. 
ny.
ny. 
Yuae
 your destiny. 
 fo rotaerc eht era uoY
creator of your destiny
creator of your destiny      
    creator of your destiny
4
-1
2


In [25]:
# exercise

a = int
b = float
c = bool
d = str

a = 10
b = 20.54
c = True
d = "I am the best"

print(a)
print(b)
print(c)
print(d)

10
20.54
True
I am the best


In [36]:
# list
lst = [10, 20, "name", -10, 30.5]

# print
print(lst)

# index
print(lst[3])
print(lst[3:5])

# multiply
print(lst * 4)

# length
print(len(lst))

# append
lst.append(40)
print(lst)

# remove by value
lst.remove("name")
print(lst)

# remove the first list element
del(lst[1])
print(lst)

# max/min
print(max(lst))
print(min(lst))

# insert
lst.insert(3, 99)
print(lst)

lst.sort(reverse = True)
print(lst)

[10, 20, 'name', -10, 30.5]
-10
[-10, 30.5]
[10, 20, 'name', -10, 30.5, 10, 20, 'name', -10, 30.5, 10, 20, 'name', -10, 30.5, 10, 20, 'name', -10, 30.5]
5
[10, 20, 'name', -10, 30.5, 40]
[10, 20, -10, 30.5, 40]
[10, -10, 30.5, 40]
40
-10
[10, -10, 30.5, 99, 40]
[99, 40, 30.5, 10, -10]


In [40]:
# Tuple
# can not be modified, immutable
# insertion order
# duplicates are ok
# different types are ok

tpl = (20, 30, 40, 50, 'xyz')
print(tpl)
print(type(tpl))
print(tpl * 3)
print(tpl.index('xyz'))

# cast
lst = [5,6, 'a']
print(tuple(lst))

(20, 30, 40, 50, 'xyz')
<class 'tuple'>
(20, 30, 40, 50, 'xyz', 20, 30, 40, 50, 'xyz', 20, 30, 40, 50, 'xyz')
4
(5, 6, 'a')


In [46]:
# set
s = {10, 20, 30, 'xyz', 10, 20, 30}
print(s)
s.update([88, 99])
print(s)
print(type(s))

# print(s * 3) will throw an error

s.remove(30)
print(s)

f = frozenset(s)
# f.update(7) will throw an error
# f.remove(10) will throw an error


{'xyz', 10, 20, 30}
{99, 10, 20, 88, 'xyz', 30}
<class 'set'>
{99, 10, 20, 88, 'xyz'}


In [48]:
# range
r = range(1, 15, 3)

for i in r:
    print(i)

1
4
7
10
13


In [52]:
# list
lst = [1, 3, 4]
b = bytes(lst)
print(type(b))
# b[1] = 0 will throw an arrow 

# bytearray assignments work
b1 = bytearray(lst)
print(type(b1))
b1[2] = 20
print(b1)

<class 'bytes'>
<class 'bytearray'>
bytearray(b'\x01\x03\x14')


In [56]:
# dict
dict1 = {1: "john", 2: "bob", 3: "bill"}
print(dict1)
print(dict1.items())
k = dict1.keys()
for i in k: print(i)
for i in dict1.values(): print(i)
print(dict1[3])
del dict1[2]
print(dict1)

{1: 'john', 2: 'bob', 3: 'bill'}
dict_items([(1, 'john'), (2, 'bob'), (3, 'bill')])
1
2
3
john
bob
bill
bill
{1: 'john', 3: 'bill'}


In [59]:
a = 20
b = 20
print(id(a))
print(id(b))
print(a is b)

a = 20
b = 10
print(id(a))
print(id(b))
print(a is b)

a = "Hi"
b = "Hi"
print(id(a))
print(id(b))
print(a is b)

94819118089760
94819118089760
True
94819118089760
94819118089440
False
139738708230768
139738708230768
True


In [63]:
# exercise
countries = ["South-Africa", "Marocco", "Spain"]
countries.append("Brazil")
del countries[2]
countries.insert(2, "Norway")

countries1 = {"Hungary", "India", "Japan"}
countries1.remove("Hungary")
countries2 = {"Switzerland"}
countries1.update(countries2)


In [4]:
# None type
def m1():
    a = 10

print(m1())
a = None

print(a)

None
None


In [6]:
# Constant
# Capitalized, can be changed but is a convention not to change this 
PI = 3.14 

In [11]:
# del
a = 10
del a
# print(a) not defined

s = 'abcd'
# del s[0] # no item deletion in a immutable type or oject, will throw an error


In [21]:
# print 
a = "Hello"
b = "world"
c = " Hi"
n = 10.4546

print(a,b,sep=" § ")
print(a,b, c,sep=" § ")

print("This is %s to the %s"%(a,b))

print("This is %s to the %s with %.3f"%(a, b, n))

print("Name is {} on {} with {}".format(a, b, n))

h = "Name is {} on {} with {}".format(a, b, n)
print(h)

Hello § world
Hello § world §  Hi
This is Hello to the world
This is Hello to the world with 10.455
Name is Hello on world with 10.4546
Name is Hello on world with 10.4546


In [7]:
# input function
for x in input("Enter three numbers: ").split():
    print(x)
    
lst = [x for x in input("Enter three numbers seperated by comma ").split(",")]
print(lst)



Enter three numbers: 3 5 6
3
5
6
Enter three numbers seperated by comma 2,3,4
['2', '3', '4']


In [8]:
n = int(input("How many Players? "))
player = {}
for i in range(n):
    name = input("Name? ")
    hobby = input("Hobby? ")
    player[name] = hobby
print(player)

How many Players? 2
Name? Tina
Hobby? Foils
Name? John
Hobby? Metal
{'Tina': 'Foils', 'John': 'Metal'}


In [2]:
# Exercise
topping = ['Vegan-cheese', 'Lettuce', 'Tomato-Sauce', 'Onions', 'Pickles', 'Garlic']
for i in topping:
    print(i)
pick = [x for x in input('Pick three toppings, seperate by space').split()]
cost = int(input('How many Sandwiches, type a number'))
print('{} is the total price'.format(cost*5))

Vegan-cheese
Lettuce
Tomato-Sauce
Onions
Pickles
Garlic
Pick three toppings, seperate by spaceVegan-cheese Lettuce Tomato-Sauce
How many Sandwiches, type a number30
150 is the total price


In [5]:
# Flow --> mostly covered in Python for absolute beginners
x = int(input("Input a number greater 10: "))
assert x>10, "Wrong number" # will show an assertion error
print("You entered ",x)


Input a number greater 10: 78
You entered  78


In [9]:
# reverse a string
s = input("Enter a string")
print(''.join(reversed(s)))

Enter a stringhallo world
dlrow ollah


In [10]:
# command line arguments
import sys
lst = sys.argv
for i in lst: print(i)
print(len(lst))

/home/haniel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py
-f
/home/haniel/.local/share/jupyter/runtime/kernel-4abbb949-6ab3-4612-b5bd-f0b0b0899215.json
3


In [15]:
# functions accessing global variables
x = 123

def display():
    x = 678
    def printLocal(x):
        print(x)
    printLocal(x)
    print(globals()['x'])
    
display()

678
123


In [16]:
# assign function to a variable

z = display
z()
z()

678
123
678
123


In [27]:
# pass function as a parameter and returning function, anything can be passed to a function, defaults
def printLocal(x):
    print(x)

def display(p=printLocal):
    x = 678
    p(x)
    print(globals()['x'])
    def returnMe():
        print("returned")
    return returnMe
    
returned = display(printLocal)
returned()
returned = display()
returned()

678
123
returned
678
123
returned


In [26]:
# recursion
def factorial1(n):
    if n == 0:
        return 1
    else:
        return n*factorial(n-1)
n = factorial1(10)
print(n)

def factorial2(n):
    if n == 0:
        result = 1
    else:
        result = n * factorial(n - 1)
    return result

n = factorial2(10)
print(n)

3628800
3628800


In [39]:
# arguments
# keyword arguments
# args and kwargs may have any name
# pass on args and kwargs
def passIt(*x, **y):
    print(x)
    print(y)

def myfun(x, *args, **kwargs):
    print(x)
    print(args)
    print(kwargs)
    for key, value in kwargs.items():
        print(key, value)
    passIt(*args, **kwargs)
    
myfun(10, 20, 30, 40, name="Kim")

10
(20, 30, 40)
{'name': 'Kim'}
name Kim
(20, 30, 40)
{'name': 'Kim'}


In [65]:
# lambdas Anonymous functions
f = lambda x:x*x
result = f(19)
print(result)

# usually used in other functions such as map, reduce ...
def cube(n):
    return n**3

print(cube(3))

f = lambda n:n**3
print(f(3))

l = lambda x: 'Yes' if x%2 == 0 else 'No'
print(l(10))

s = lambda a,b: a + b
s(3,4)

lst = [10, 2, 33, 45, 89, 2]
lst = list(filter(lambda x: x%2==0, lst))
print(lst)

# map
lst = list(map(lambda n: n*2, lst))
print(lst)

# reduce
from functools import reduce
#reduce(function, sequence)
lst = reduce(lambda x,y:x+y, lst)
print(lst)

# decorator
def decor(fun):
    def inner():
        result = fun()
        return result * 2
    return inner

def num():
    return 5

resultFun = decor(num)
print(resultFun())

# @decor
# decorator
def decor(fun):
    def inner():
        result = fun()
        return result * 2
    return inner

@decor
def num():
    return 5

print(num())

# chain decorators
def square(fun):
    def inner():
        n = fun()
        return n/3
    return inner

@square
@decor
def num1():
    return 5

print(num1())

print("\n")
# generators
def customgen(x,y):
    while x < y:
        yield x
        x += 1
        
result = customgen(10,18)

for i in result:print(i)
    
# dont use keywords for variables, functions etc. so lets check them
import keyword
print(keyword.kwlist)

361
27
27
Yes
[10, 2, 2]
[20, 4, 4]
28
10
10
3.3333333333333335


10
11
12
13
14
15
16
17
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [6]:
# modules
from math import *

print(sqrt(9))
print(ceil(8))
print(floor(7.9))
print(fabs(-2.2))

# print module functions
print(dir(math))

# help 
help(math)


3.0
8
7
2.2
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']
Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.7/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathema

In [18]:
# modules
from random import *

for i in range(3):
    print(random())
for i in range(3):
    print(randint(1,50))
for i in range(3):
    print(uniform(1,50))
for i in range(3):
    print(randrange(5,50, 5))
lst = ['22', 'super', 'jfk', 38, "ist", 'hey']
for i in range(5):
    print(choice(lst))

0.9338747109190088
0.7503729423102764
0.8739319235827789
16
49
36
46.20528493933439
22.14159425759591
8.679557835618121
45
15
30
super
22
jfk
jfk
jfk


In [28]:
# list comprehension
lst = []
for x in range(1,11):
    lst.append(x**3)
print(lst)

lst = [x**3 for x in range(1,11)]
print(lst)

lst = [x for x in range(0,21) if x%2==0]
print(lst)

a = [2,3,4,5,6]
b = [8,5,2,-1,-4]
z = [a[i] * b[i] for i in range(1,len(a))]
print(z)

a = [2,4,6,8]
b = [1,2,6,4]
result = []
z = [a[i] for i in range(1,len(a)) if a[i] == b[i]]
print(z)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[15, 8, -5, -24]
[6]


In [31]:
# OOP
class Product:
    def __init__(self):
        self.name = 'IPhone!'
        self.description = 'It\'s awesome?'
        self.price = 700

p1 = Product()
print(p1.name, p1.description, p1.price)

IPhone! It's awesome? 700


In [36]:
class Course:
    def __init__(self, name, ratings):
        self.name = name
        self.ratings = ratings
        
    def average(self):
        numberOfRatings = len(self.ratings)
        average = sum(self.ratings)/numberOfRatings
        print("Average Ratings for ", self.name, " is ", average)

c1 = Course("Java Data course:", [1,9,9,4,5])
print(c1.name, c1.ratings)

c2 = Course("Java Web course:", [5,6,3,4,5])
print(c2.name, c2.ratings)

c1.average()
c2.average()

Java Data course: [1, 9, 9, 4, 5]
Java Web course: [5, 6, 3, 4, 5]
Average Ratings for  Java Data course:  is  5.6
Average Ratings for  Java Web course:  is  4.6


In [65]:
# setter and getter are the mutuator methods

class Programmer:
    major = 'STEM'
    numberOfProgrammer = 0
    def __init__(self):
        self.__college = True # __ hide field
        Programmer.numberOfProgrammer += 1
    def setName(self, n):
        self.name = n
    def getName(self):
        return self.name
    def setSalary(self, sal):
        self.salary = sal
    def getSalary(self):
        return self.salary
    def setTechnologies(self, technologies):
        self.technologies = technologies
    def getTechnologies(self):
        return self.technologies
    
    # inner class
    class Greeting:
        def greet(self):
            print("Hello people!")
            
    def __del__(self):
        print("inside destructor")
    
    @staticmethod
    def displayCount():
        print(Programmer.numberOfProgrammer)
        
    
p1 = Programmer()
p1.setName("Zeni")
p1.setSalary(100000)
p1.setTechnologies(["java", "docker", "ansible"])
speak = p1.Greeting()
speak.greet()

print(p1.name, p1.salary, p1.technologies, p1.major)
p1 = None

p2 = Programmer()
p2.setName("Kevin")
p2.setSalary(110000)
p2.setTechnologies(["python", "kubernetes", "aws"])

print(p2.name, p2.salary, p2.technologies, p2.major)

Programmer.displayCount()    

# access a 'private' field, name mangling
print(p2._Programmer__college)

Hello people!
Zeni 100000 ['java', 'docker', 'ansible'] STEM
inside destructor
inside destructor
Kevin 110000 ['python', 'kubernetes', 'aws'] STEM
2
True


In [66]:
# methods any name, when invorked, any number of times
# constructor __init__, authomatically

In [67]:
import gc

print(gc.isenabled())
gc.disable()
print(gc.isenabled())
gc.enable()
print(gc.isenabled())

True
False
True


In [30]:
# Inheritance
# Method overriding, achieve 'runtime polymorphism for free' with dynamic types in Python
# Abstract classes and interfaces
from abc import abstractmethod, ABC

# ABC from abc
# abstract class can't be instantiated
# becomes an interface with all methods abstracted
class BMW(ABC):
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
    @abstractmethod    
    def start(self):
        pass
    @abstractmethod
    def stop(self):
       pass    
    # child classes need a drive method
    @abstractmethod
    def drive(self):
        pass
        
class ThreeSeries(BMW):
    def __init__(self, cruiseControlEnabled, make, model, year):
        BMW.__init__(self, make, model, year)
        self.cruiseControlEnabled = cruiseControlEnabled
        
    def display(self):
        print(self.cruiseControlEnabled)
        
    def drive(self):
        print("three series is being driven")
        
    # overriding respective method for interface
    def start(self):
        print("starting the three series")
    # super with methods
    def stop(self):
        super().stop()
        print("end ride, please drive again soon")
        
class FiveSeries(BMW):
    def __init__(self, parkingAssistEnabled, make, model, year):
        # use super instead of BMW.__init__
        super().__init__(make, model, year)
        self.parkingAssistEnabled = parkingAssistEnabled
    # overriding respective method for interface
    def start(self):
        print("starting the five series")
    # super with methods
    def stop(self):
        super().stop()
        print("end ride, please rate your ride in the app")
        
    def drive(self):
        print("five series is being driven")

threeSeries = ThreeSeries(True, "BMW", "328i", "2018")
print(threeSeries.cruiseControlEnabled)
print(threeSeries.make)
print(threeSeries.model)
print(threeSeries.year)
threeSeries.start() # inherited
threeSeries.display() # only in three series
threeSeries.drive()
threeSeries.stop()

fiveSeries = FiveSeries(True, "BMW", "5x", "2020")
fiveSeries.start()
fiveSeries.drive()
fiveSeries.stop()

True
BMW
328i
2018
starting the three series
True
three series is being driven
end ride, please drive again soon
starting the five series
five series is being driven
end ride, please rate your ride in the app


In [14]:
# DuckTyping, polymorphism
# pass an object to a function
def talk(obj):
    obj.talk()
    
class Duck:
    def talk(self):
        print("Human, you don't understand duck talk")

class Human:
    def talk(self):
        print("Duck, you dont undertand human talk")

h=Human()
talk(h)

d=Duck()
talk(d)


Duck, you dont undertand human talk
Human, you don't understand duck talk
Starting Airbus Engine
Starting Airbus Engine


In [15]:
# dependency injection
class Flight:
    def __init__(self, engine):
        self.engine = engine
    def startEngine(self):
        self.engine.start()

class AirbusEngine:
    def start(self):
        print("Starting Airbus Engine")

class BoeingEngine:
    def start(self):
        print("Starting Boeing Engine")
        
ae = AirbusEngine()
f = Flight(ae)
f.startEngine()

be = AirbusEngine()
f = Flight(ae)
f.startEngine()


Starting Airbus Engine
Starting Airbus Engine


In [18]:
# Operator overloading, polymorphic operator
x = 10
y = 20

print(x + y)

s1 = "Hello "
s2 = "how are you"

print(s1 + s2)

l1 = [1,2,3]
l2 = [4,5,6]
print(l1 + l2)

30
Hello how are you
[1, 2, 3, 4, 5, 6]


In [10]:
# exceptions
# baseException
#   Exception
#     standardError EOFError, ZeroDivisionError, IndentationError
#     warning DepreciatedWarning, importWarning

# Handling exceptions
try: 
    f = open("myfile", "w")
    a,b = [int(x) for x in input("Enter two numbers: ").split()]
    c = a/b
    f.write("Writing %d into file" %c)
    f.close()
except ZeroDivisionError:
    print("Division by zero is not allowed")
    print("Please enter a non zero number")
else:
    print("You have entered a non zero number")
finally:
    f.close()
    print("file closed")
print("Code after exception")

Enter two numbers: 4 0
Division by zero is not allowed
Please enter a non zero number
file closed
Code after exception


In [11]:
# custom error
class OverTheLimitException(Exception)
    def __init__(self,msg)
        self.msg = msg

def withdrawl(amount).
    if(amount>2000):
        raise OverTheLimitException("Withdrawal over 2000 per day is not possible")
        
withdrawl(3000)
        

SyntaxError: invalid syntax (1928694544.py, line 2)

In [ ]:
# Logging in action
import logging

logging.basicConfig(filename="mylog.log", encoding='utf-8', level=logging.DEBUG)
logging.error("Error")
logging.critical("Error")
logging.warning("Error")
logging.debug("Error")
logging.info("Error")
              

In [20]:
# Logging exception handling demo
try: 
    f = open("myfile", "w")
    a,b = [int(x) for x in input("Enter two numbers: ").split()]
    logging.info("Division in progress")
    c = a/b
    f.write("Writing %d into file" %c)
    f.close()
except ZeroDivisionError:
    print("Division by zero is not allowed")
    print("Please enter a non zero number")
    logging.error("Division by zero")
else:
    print("You have entered a non zero number")
finally:
    f.close()
    print("file closed")
print("Code after exception")

Enter two numbers: 2 0


ERROR:root:Division by zero


Division by zero is not allowed
Please enter a non zero number
file closed
Code after exception


In [22]:
# assertion case
try: 
    num = int(input("Enter an even number:"))
    assert num%2==0, "you have entered an odd number"
except AssertionError as obj:
    print(obj)
print("after assertion")
    


Enter an even number:7
you have entered an odd number
after assertion


In [11]:
# file i/o
# w write
# r read from the beginning to the end
# a append
# w+ write and read
# r+ read, write and append
# a+ appending and reading
# x 
# f=open("fileName", "mode", "buffer")

# multiple lines
import os, sys

f = open("myfile.txt", "w")
s = input("Enter text: ")
f.write(s)
f.close()

f = open("myfile.txt", "r")
s = f.read()
print(s)
f.close()




Enter text: #
#


In [13]:
# multiple lines
f = open("myfile.txt", "w")
print("Enter Text (Type # when you are done)")

s = ''
while s != '#':
    s = input()
    f.write(s + '\n')
    
f.close()

Enter Text (Type # when you are done)
#


In [14]:
# cehck if file exists

if os.path.isfile('myfile.txt'):
    f = open('myfile.txt', 'r')
    s = f.read()
    print(s)
    f.close()
else:
    print("File does not exist")
    
if os.path.isfile('myfile123.txt'):
    f = open('myfile.txt', 'r')
    s = f.read()
    print(s)
    f.close()
else:
    print("File does not exist")



#

File does not exist


In [16]:
# pickle and unpickle object (serialize)
import pickle, student

f = open("student.dat", "wb")
s = student.Student(123, "John", 90)
pickle.dump(s, f)
f.close()

f = open("student.dat", "rb")
obj = pickle.load(f)
obj.display()


123 John 90


In [21]:
# Regular expressions I
# - pattern, search, email, password, validate, regex
# - re - match, search, findall, split, sub

# \d digit
# \D non-digit
# \s whitespace
# \S non-whitespace
# \w numeric
# \W non-alpha numeric
# \b whitespace around words
# \A matches at the beginning of the string, search at the beginning
# \Z matches at the end of the string 
# + one or more digits
# * zero or more 
# {m} exactly m occurences
# ? zero or one
# {m,n} min m to max n occurences, 0 to infinity if nothing specified

import re

s = "Take up one idea. One idea at a time."

# returns a  SRE_Match object
result = re.search(r'o\w\w', s) # o followed by any four characters
print(result.group())

# returns a list
result = re.findall(r'[oO]\w\w', s)
print(result)

# returns a  SRE_Match object
result = re.match(r'o\w\w', s)
result1 = re.match(r'T\w\w', s)
print(result)
print(result1.group())

s = "Take up 1 One or or 23 idea. One idea maybe 45 at a time."
result = re.findall(r'O\w{1,2}', s)
print(result)

result = re.split(r'\d+', s)
print(result)

result = re.sub(r'idea', 'alternatives', s)
print(result)



one
['one', 'One']
None
Tak
['One', 'One']
['Take up ', ' One or or ', ' idea. One idea maybe ', ' at a time.']
Take up 1 One or or 23 alternatives. One alternatives maybe 45 at a time.


In [28]:
# Regular expressions II
# - pattern, search, email, password, validate, regex
# - re - match, search, findall, split, sub

# \d digit
# \D non-digit
# \s whitespace
# \S non-whitespace
# \w numeric
# \W non-alpha numeric
# \b whitespace around words
# \A matches at the beginning of the string, search at the beginning
# \Z matches at the end of the string 
# + one or more digits
# * zero or more 
# {m} exactly m occurences
# ? zero or one
# {m,n} min m to max n occurences, 0 to infinity if nothing specified

s = "Take up one idea. One idea at a time."

# Quantifiers
# one or more of the preceding regular expression
result = re.findall(r'[oO]\w+', s)
print(result)
# zero or more of the preceding regular expression
result = re.findall(r'[oO]\w*', s)
print(result)
# zero or one of the preceding regular expression
result = re.findall(r'[oO]\w?', s) 
print(result)

print()
# m of the preceding regular expression, o or O followed by one alphanumeric character
result = re.findall(r'[oO]\w{1}', s) 
print(result)
result = re.findall(r'[oO]\w{2}', s) 
print(result)
result = re.findall(r'[oO]\w{3}', s) 
print(result)

print()
# m to n of the preceding regular expression
result = re.findall(r'[oO]\w{1,2}', s) 
print(result)



['one', 'One']
['one', 'One']
['on', 'On']

['on', 'On']
['one', 'One']
[]

['one', 'One']


In [30]:
# Matching dates
s = "Take up one idea. 1-3-2012. One idea at a time in 12-2-2022."
result = re.findall(r'\d{1,2}-\d{1,2}-\d{4}', s)
print(result)

['1-3-2012', '12-2-2022']


In [34]:
# Special characters
# \ escape special character
# . all except a new line
# ^ all at the beginning of a string
# $ at the end of a string
# [...] in the range of a string e.g. a-z
# [^...] all that are not in the brackets
# (...) match the regular expression
# (R|S) either regular expression R or regular expression S
s = "Take up one idea. 1-3-2012. One idea at a time in 12-2-2022."
result = re.findall(r'\d{1,2}-\d{1,2}-\d{4}', s)
print(result)

result = re.search(r'^O\w', s)
print(result)

result = re.search(r'^T\w', s)
print(result.group())

result = re.search(r'^T\w*', s)
print(result.group())

['1-3-2012', '12-2-2022']
None
Ta
Take


In [44]:
# date and time
# epoch start since jan 1st 1970
# ctime() time
# datetime datetime
# sleep()
# perf_counter()

# time.time()

import time, datetime
epochseconds = time.time()
print(epochseconds)

s = time.ctime(epochseconds)
print(s)

dt = datetime.datetime.today()
print(dt)
print("Current Date: {}-{}-{} {}:{}:{}".format(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second))





1643282358.9954274
Thu Jan 27 12:19:18 2022
2022-01-27 12:19:19.000179
Current Date: 2022-1-27 12:19:19


In [48]:
# create dates with combine
from datetime import *

d = date(2018, 7, 21)
t = time(12, 45)

dt = datetime.combine(d,t)
print(dt)

2018-07-21 12:45:00


In [54]:
# sort dates, sleep, execution time,
from datetime import *
import time


startTime = time.perf_counter()

ldates = []
d1 = date(2016, 8, 12)
d2 = date(2017, 8, 12)
d3 = date(2018, 8, 12)
d4 = date(2016, 7, 12)
d5 = date(2017, 8, 30)
d6 = date(2018, 9, 12)

ldates.append(d1)
ldates.append(d2)
ldates.append(d3)
ldates.append(d4)
ldates.append(d5)
ldates.append(d6)

ldates.sort()

time.sleep(3)

for d in ldates:
    print(d)
    
endTime = time.perf_counter()

print()
print("Excecution time: {}s".format(endTime - startTime))


2016-07-12
2016-08-12
2017-08-12
2017-08-30
2018-08-12
2018-09-12

Excecution time: 3.0068739710004593 s


In [56]:
# Treads Main Thread
import threading

print("Current Thread that is running:", threading.current_thread().getName())

if threading.current_thread() == threading.main_thread():
    print("Main thread")
else:
    print("Some other thread")

Current Thread that is running: MainThread


In [62]:
# Create the first thread, new thread from the main thread
from threading import Thread

def displayNumbers():
    i = 0
    print("Current Thread that is running in displayNumers:", threading.current_thread().getName())
    while(i <= 10):
        print(i)
        i += 1

print("Current Thread that is running:", threading.current_thread().getName())
t = Thread(target=displayNumbers)
t.start()

Current Thread that is running: MainThread
Current Thread that is running in displayNumers: Thread-10
0
1
2
3
4
5
6
7
8
9
10


In [64]:
# Create thread derivig from class

class MyThread(Thread):
    def run(self):
        i = 0
        print("Current Thread that is running in displayNumers:", threading.current_thread().getName())
        while(i <= 10):
            print(i)
            i += 1

print("Current Thread that is running:", threading.current_thread().getName())
t = MyThread()
t.start()

Current Thread that is running: MainThread
Current Thread that is running in displayNumers: Thread-12
0
1
2
3
4
5
6
7
8
9
10


In [69]:
# threading using a class

class MyThread:
    
    def displayNumbers(self):
        i = 0
        print("Current Thread that is running in displayNumers:", threading.current_thread().getName())
        while(i <= 10):
            print(i)
            i += 1

print("Current Thread that is running:", threading.current_thread().getName())
obj = MyThread()
t = Thread(target=obj.displayNumbers)
t.start()

t1 = Thread(target=obj.displayNumbers)
t1.start()

t2 = Thread(target=obj.displayNumbers)
t2.start()


Current Thread that is running: MainThread
Current Thread that is running in displayNumers: Thread-23
0
1
2
3
4
5
6
7
8
9Current Thread that is running in displayNumers: Thread-24
10

Current Thread that is running in displayNumers:0
1
2
3 Thread-25
0
1
2
3
4
5
6
7
8
9
10

4
5
6
7
8
9
10


In [73]:
# threading using a class, multithreading in action, delay in threads: push a thread into sleep
import time 

class MyThread:
    
    def displayNumbers(self):
        i = 0
        print("Current Thread that is running in displayNumers:", threading.current_thread().getName())
        time.sleep(1)
        while(i <= 10):
            print(i)
            i += 1

print("Current Thread that is running:", threading.current_thread().getName())
obj = MyThread()
t = Thread(target=obj.displayNumbers)
t.start()

t1 = Thread(target=obj.displayNumbers)
t1.start()

t2 = Thread(target=obj.displayNumbers)
t2.start()

Current Thread that is running: MainThread
Current Thread that is running in displayNumers: Thread-35
Current Thread that is running in displayNumers: Thread-36
Current Thread that is running in displayNumers: Thread-37
0
1
2
3
4
5
6
7
8
9
10
00

1
2
3
4
15
6
7
8
9
2
3
4
5
6
7
8
9
10

10


In [75]:
# usecase
from threading import *

class BookMyBus:
    
    def buy(self):
        print("Confirming a seat")
        print("Processing the payment")
        print("Printing the ticket")
        
obj = BookMyBus()
t1 = Thread(target=obj.buy())
t2 = Thread(target=obj.buy())
t3 = Thread(target=obj.buy())

t1.start()
t2.start()
t3.start()

Confirming a seat
Processing the payment
Printing the ticket
Confirming a seat
Processing the payment
Printing the ticket
Confirming a seat
Processing the payment
Printing the ticket


In [ ]:
# Thread synchronization
# thread mutex, semaphore
# first acquire a lock, then no thread can use the object until release
# semaphore uses a counter 



In [87]:
# usecase, synchronize with a lock/semaphore
from threading import *

class BookMyBus:
    
    def __init__(self, availableSeats):
        self.availableSeats = availableSeats
        self.l = Lock() # or self.l = Semaphore()
        
    def buy(self, seatsRequested):
        self.l.acquire()
        print("Seats left: ", self.availableSeats)
        if(self.availableSeats >= seatsRequested):
            print("Confirming a seat")
            print("Processing the payment")
            print("Printing the ticket")
            self.availableSeats -= seatsRequested
        else:
            print("Not enough seats available")
        self.l.release()

obj = BookMyBus(9)
t1 = Thread(target=obj.buy, args=(3,))
t2 = Thread(target=obj.buy, args=(4,))
t3 = Thread(target=obj.buy, args=(3,))

t1.start()
t2.start()
t3.start()

Seats left:  9
Confirming a seat
Processing the payment
Printing the ticket
Seats left:  6
Confirming a seat
Processing the payment
Printing the ticket
Seats left:  2
Not enough seats available


In [93]:
# Thread communication, using a flag
from threading import *
from time import *

class Producer: 
    
    def __init__(self):
        self.products = []
        self.ordersplaced = False
        
    def produce(self):
        for i in range(1,5):
            self.products.append("Product "+str(i))
            sleep(1)
            print("item added")
        self.ordersplaced = True

class Consumer:
    def __init__(self, prod):
        self.prod = prod
        
    def consume(self):
        while self.prod.ordersplaced == False:
            sleep(0.2)
        print("Orders shipped ", str(self.prod.products))
        
p = Producer()

c = Consumer(p)

t1 = Thread(target=p.produce())
t2 = Thread(target=c.consume())


item added
item added
item added
item added
Orders shipped  ['Product 1', 'Product 2', 'Product 3', 'Product 4']


In [95]:
# Thread communication, using wait and notify
from threading import *
from time import *

class Producer: 
    
    def __init__(self):
        self.products = []
        self.c = Condition()
        
    def produce(self):
        self.c.acquire()
        
        for i in range(1,5):
            self.products.append("Product "+str(i))
            sleep(1)
            print("item added")
        self.c.notify()
        self.c.release()

class Consumer:
    def __init__(self, prod):
        self.prod = prod
        
    def consume(self):
        self.prod.c.acquire()
        self.prod.c.wait(timeout = 0)
        self.prod.c.release()
        print("Orders shipped ", str(self.prod.products))
        
p = Producer()

c = Consumer(p)

t1 = Thread(target=p.produce())
t2 = Thread(target=c.consume())


item added
item added
item added
item added
Orders shipped  ['Product 1', 'Product 2', 'Product 3', 'Product 4']


In [102]:
# Queues and thread communication
import random
import time
import queue
from threading import *

def producer(q):
    i = 0
    while i<5:
        print("producing\n")
        q.put(random.randint(1,50))
        print("produced\n")
        i += 1
        
def consumer(q):
    i = 0
    while i<5:
        print("ready to consume\n")
        print("consume data", q.get(),'\n')
        time.sleep(3)
        
q = queue.Queue()
t1 = Thread(target=producer, args=(q,))
t2 = Thread(target=consumer, args=(q,))
t1.start()
t2.start()

producing
ready to consume


produced
consume data
producing

produced

producing

produced

producing

 2 produced

producing



produced

ready to consume

consume data 35 

ready to consume

consume data 28 

ready to consume

consume data 16 

ready to consume

consume data 50 

ready to consume



In [104]:
# three types of queue
import queue

q = queue.Queue()
q.put(400)
q.put(100)
q.put(500)
q.put(50)

while not q.empty():
    print(q.get(), end=' ')
print()
lq = queue.LifoQueue()
lq.put(400)
lq.put(100)
lq.put(500)
lq.put(50)

while not lq.empty():
    print(lq.get(), end=' ')
print()
pq = queue.PriorityQueue()
pq.put(400)
pq.put(100)
pq.put(500)
pq.put(50)

while not pq.empty():
    print(pq.get(), end=' ')

400 100 500 50 
50 500 100 400 
50 100 400 500 

In [108]:
# types for queue: use tuples
q = queue.Queue()
q.put((400, "John"))
q.put((100, "Bob"))
q.put((500, "Ahmed"))

while not q.empty():
    print(q.get(), end=' ')
print()
q.put((400, "John"))
q.put((100, "Bob"))
q.put((500, "Ahmed"))  
while not q.empty():
    print(q.get()[1], end=' ')
print()

(400, 'John') (100, 'Bob') (500, 'Ahmed') 
John Bob Ahmed 


In [112]:
# server, download html
import urllib.request

try:
    url = urllib.request.urlopen("https://www.python.org/")
    content = url.read()
    url.close()
except urllib.error.HTTPError:
    print("page not found")
f = open('python.html', 'wb')
f.write(content)
f.close()

In [115]:
# images, download image
import urllib.request

try:
    url = "https://www.python.org/static/img/python-logo@2x.png"
    urllib.request.urlretrieve(url, "python.png")
except urllib.error.HTTPError:
    print("image not found")

In [2]:
# socket programming: socket, connect - socket, bind, listen, accept, send/recv, close
# import socket
#
# host = "localhost"
# port = 4001
# 
# s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
# 
# s.bind((host,port))
# print("Server listening on port:",port)
# s.listen(1)
# 
# c, addr = s.accept()
# print("Connection from:", str(addr))
# c.send(b"Hello, how are you?")
# c.send("bye".encode())
# c.close()

In [3]:
#client run with .py
# import socket
# s = socket.socket()
#
# s.connect(("localhost", 4000))
# msg = s.recv(1024)
#
# while msg:
#     print("Received: ", msg.decode())
#     msg = s.recv(1024)
#    
# s.close()

In [ ]:
host = 'localhost'
port = 6767

s = socket.socket()

s.connect8("localhost", port))

input("Enter a filename:")

s.send(fileName.encode())

content = s.recv(1024)

print(content.decode())

s.close()

In [5]:
# sending e-mail
# create message body, subject, from , to
# smtp server login, send message
# quit

# import smtplib
# from email.mime.text import MIMEText

# body = "This is a test email. How are you?"
# msg = MIMEText(body)
# msg['From'] = "a@b.com"
# msg['To'] = "c@d.com"
# msg['Subject'] = "Hello"

# server = smtplib.SMTP('smtp.b.com', 587)

# server.starttls()

# server.login("username", "password")

# server.send(msg)

# print("Mail send")

# server.quit()

In [ ]:
# database operations, CRUD operations
# use docker for mysql and mongo

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
carr = np.array(['arr', 'ay'])
sarr = np.array(['python', 'django', 'django rest'])
print(arr)
print(carr)
print(sarr)

[1 2 3 4 5]
['arr' 'ay']
['python' 'django' 'django rest']


In [11]:
from numpy import *
larr = linspace(0, 100, 50) # is also default
print(larr)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [12]:
lgarr = logspace(0,100)
print(lgarr)

[1.00000000e+000 1.09854114e+002 1.20679264e+004 1.32571137e+006
 1.45634848e+008 1.59985872e+010 1.75751062e+012 1.93069773e+014
 2.12095089e+016 2.32995181e+018 2.55954792e+020 2.81176870e+022
 3.08884360e+024 3.39322177e+026 3.72759372e+028 4.09491506e+030
 4.49843267e+032 4.94171336e+034 5.42867544e+036 5.96362332e+038
 6.55128557e+040 7.19685673e+042 7.90604321e+044 8.68511374e+046
 9.54095476e+048 1.04811313e+051 1.15139540e+053 1.26485522e+055
 1.38949549e+057 1.52641797e+059 1.67683294e+061 1.84206997e+063
 2.02358965e+065 2.22299648e+067 2.44205309e+069 2.68269580e+071
 2.94705170e+073 3.23745754e+075 3.55648031e+077 3.90693994e+079
 4.29193426e+081 4.71486636e+083 5.17947468e+085 5.68986603e+087
 6.25055193e+089 6.86648845e+091 7.54312006e+093 8.28642773e+095
 9.10298178e+097 1.00000000e+100]


In [13]:
aarr = arange(1,20)
print(aarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [14]:
as_arr = arange(1,20, 0.5) # with step value
print(as_arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [15]:
print(zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
print(ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
# math functions
from numpy import *
a1 = array([1,2,3,4])
a2 = array([5,6,7,8])
print(a1+a2)
print(a1-2)
print(sin(a1))
print(cos(a1))
print(mean(a1))
print(std(a1))
print(abs(a1))
print(min(a1))
print(max(a1))
print(sqrt(a1))
print(sum(a1))

[ 6  8 10 12]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
2.5
1.118033988749895
[1 2 3 4]
1
4
[1.         1.41421356 1.73205081 2.        ]
10


In [26]:
# array comparison
a1 = array([10, 31, 50, 71, 110])
a2 = array([20, 40, 60, 80, 100])

print(a1<a2)
print(a1>a2)
print(a1==a2)
print(a1<=a2)
# ...
print(all(a1<=a2))
print(logical_and(a1>10, a1<101))
print(logical_and(a1>10, a1<101))
print(where(a1%2==0, a1, 0))

[ True  True  True  True False]
[False False False False  True]
[False False False False False]
[ True  True  True  True False]
False
[False  True  True  True False]
[False  True  True  True False]
[ 10   0  50   0 110]


In [29]:
# copying arrays
a1 = arange(1,10)
a2 = a1.view()
print("shallow copy")
print('a1', a1)
print('a2', a2)
a2[3] = 40
print("after modification")
print('a1', a1)
print('a2', a2)
print()
print("deep copy")
a1 = arange(1,10)
a2 = a1.copy()
a2[3] = 40
print("after modification")
print('a1', a1)
print('a2', a2)

shallow copy
a1 [1 2 3 4 5 6 7 8 9]
a2 [1 2 3 4 5 6 7 8 9]
after modification
a1 [ 1  2  3 40  5  6  7  8  9]
a2 [ 1  2  3 40  5  6  7  8  9]

deep copy
after modification
a1 [1 2 3 4 5 6 7 8 9]
a2 [ 1  2  3 40  5  6  7  8  9]


In [32]:
# slicing
from numpy import *

a = arange(3,12)
print(a[3:])
print(a[1:8:2])

[ 6  7  8  9 10 11]
[ 4  6  8 10]


In [44]:
# multidimensional arrays
from numpy import *

a1 = np.array([1,  2,  3, 40, 5,  6,  7,  8])
a2 = np.array([[1,  2,  3, 40],[  5,  6,  7,  8]])
a3 = np.array([[[1,  2],[ 3, 40]],[[  5,  6],[   7,  8]]])

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

print(a1.shape)
print(a2.shape)
print(a3.shape)

a2.shape = (4,2)
print(a2)

print(a1.size)
print(a2.size)
print(a3.size)

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)

1
2
3
(8,)
(2, 4)
(2, 2, 2)
[[ 1  2]
 [ 3 40]
 [ 5  6]
 [ 7  8]]
8
8
8
8
8
8
int64
int64
int64
64
64
64


In [50]:
# a few functions
from numpy import *

a1 = arange(12)
print('a1', a1)

a2 = reshape(a1, (4,3))
print('a2', a2)
a3 = reshape(a1, (2,2,3))
print('a3', a3)
print(a3.flatten())
print()
print(ones((2,3))) # datatype float
print(ones((2,3), int))
print(zeros((2,3), int))

a1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a2 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a3 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


## mysql, postgres mongodb

In [33]:
# ! pip install mysql-connector-python
import mysql.connector

In [7]:
conn = mysql.connector.connect(host = 'localhost', database = 'mydb', user = 'root', password = 'root')

if conn.is_connected():
    print("Connected to mysql db")
    
conn.close()

Connected to mysql db


In [10]:
# CRUD operations, do twice but insert first : insert into emp values(1,'John', 10000)
conn = mysql.connector.connect(host = 'localhost', database = 'mydb', user = 'root', password = 'root')

if conn.is_connected():
    print("Connected to mysql db")
    
cursor = conn.cursor()

cursor.execute('select * from emp')

row = cursor.fetchone()

while row is not None:
    print(row)
    row = cursor.fetchone()
    
cursor.close()
    
conn.close()

Connected to mysql db
(1, 'John', 10000)
(2, 'Bob', 20000)


In [16]:
# fetch all
# do twice but insert first : insert into emp values(1,'John', 10000)
conn = mysql.connector.connect(host = 'localhost', database = 'mydb', user = 'root', password = 'root')

if conn.is_connected():
    print("Connected to mysql db")
    
cursor = conn.cursor()

cursor.execute('select * from emp')

rows = cursor.fetchall()

print("Number of rows: ", cursor.rowcount)

for row in rows:
    print(row)
    
cursor.close()
    
conn.close()

Connected to mysql db
Number of rows:  2
(1, 'John', 10000)
(2, 'Bob', 20000)


In [21]:
# Create
conn = mysql.connector.connect(host = 'localhost', database = 'mydb', user = 'root', password = 'root')

if conn.is_connected():
    print("Connected to mysql db")
    
cursor = conn.cursor()

try:
    cursor.execute("insert into emp values (4, 'Fred', 35000)")
    conn.commit()
    print("Added employee successfully")
except:
    conn.rollback()

cursor.execute('select * from emp')

rows = cursor.fetchall()

print("Number of rows: ", cursor.rowcount)

for row in rows:
    print(row)
    
cursor.close()
    
conn.close()

Connected to mysql db
Added employee successfully
Number of rows:  3
(1, 'John', 10000)
(2, 'Bob', 20000)
(4, 'Fred', 35000)


In [20]:
# Delete

def delete(id):
    conn = mysql.connector.connect(host = 'localhost', database = 'mydb', user = 'root', password = 'root')

    if conn.is_connected():
        print("Connected to mysql db")

    cursor = conn.cursor()
    str = "delete from emp where id='%d'"
    args=id

    try:
        cursor.execute(str % args)
        conn.commit()        
        print("Deleted employee successfully")
    except:
        conn.rollback()
    finally:
        cursor.execute('select * from emp')
        rows = cursor.fetchall()
        print("Number of rows: ", cursor.rowcount)
        for row in rows:
            print(row)        
        cursor.close()
        conn.close()
        
delete(3)

Connected to mysql db
Deleted employee successfully
Number of rows:  2
(1, 'John', 10000)
(2, 'Bob', 20000)


In [23]:
# For postgres
# setup via docker, see added files
#create database employeedb;
#\c employeedb;
#create table employee (id serial primary key,name varchar(30),sal real);
#create user test with encrypted password 'password';
#grant privileges on database employeedb to test;
#grant all privileges on table employee to test;
#grant all privileges on sequence employee_id_seq to test;
!pip install psycopg2-binary



     |████████████████████████████████| 3.0 MB 4.4 MB/s eta 0:00:01


In [24]:
import psycopg2

In [32]:
connection = psycopg2.connect(database="employeedb", user="test", password="password", host="127.0.0.1", port="5432")

print("connected to employedb")

cursor = connection.cursor()

cursor.execute("insert into employee (name, sal) values ('Firstname', 2000000)")
connection.commit()

cursor.execute("select * from employee")
rows = cursor.fetchall()

for row in rows:
    print("ID", row[0])
    print("Name", row[1])
    print( row[2])

print("employer created")

connection.close()

In [34]:
# mongodb
!pip install pymongo

     |████████████████████████████████| 452 kB 3.7 MB/s eta 0:00:01


In [40]:
import pymongo

from pymongo import MongoClient
# client = MongoClient('192.168.2.104', 21017)
#client = MongoClient(host='localhost',
#                     port=21017,
#                     username='mongo',
#                     password='mongo',
#                     authMechanism='SCRAM-SHA-256')
client = MongoClient("mongodb://localhost:27017/")

database = client['mydb']
print('Database Created')
collection = database['product']
print('Collection Database')
product = {
    "name": "iPhone",
    "price": 340
}

result = collection.insert_one(product)
print(result.inserted_id)

Database Created
Collection Database


In [41]:
from pymongo import MongoClient
# client = MongoClient('192.168.2.104', 21017)
#client = MongoClient(host='localhost',
#                     port=21017,
#                     username='mongo',
#                     password='mongo',
#                     authMechanism='SCRAM-SHA-256')
client = MongoClient("mongodb://localhost:27017/")

database = client['mydb']
print('Database Created')
collection = database['product']
print('Collection Database')
product = [{
    "name": "IPhone",
    "price": 1000
},  {
    "name": "Mac Book",
    "price": 2000
},  {
    "name": "Dell",
    "price": 1500
}]

result = collection.insert_many(product)
print(result.inserted_ids)

Database Created
Collection Database
[ObjectId('61f6a277c8144f68349798e8'), ObjectId('61f6a277c8144f68349798e9'), ObjectId('61f6a277c8144f68349798ea')]


In [43]:
collection = database['product']
print(collection.find_one())
cursor = collection.find()
for e in cursor:
    print(e)

{'_id': ObjectId('61f6a0e2c8144f68349798e4'), 'name': 'iPhone', 'price': 340}
{'_id': ObjectId('61f6a0e2c8144f68349798e4'), 'name': 'iPhone', 'price': 340}
{'_id': ObjectId('61f6a0f3c8144f68349798e6'), 'name': 'iPhone', 'price': 340}
{'_id': ObjectId('61f6a277c8144f68349798e8'), 'name': 'IPhone', 'price': 1000}
{'_id': ObjectId('61f6a277c8144f68349798e9'), 'name': 'Mac Book', 'price': 2000}
{'_id': ObjectId('61f6a277c8144f68349798ea'), 'name': 'Dell', 'price': 1500}


In [45]:
# filter data to find data
collection = database['product']

cursor = collection.find({"name": "Dell"})
for e in cursor:
    print(e)

{'_id': ObjectId('61f6a277c8144f68349798ea'), 'name': 'Dell', 'price': 1500}


In [47]:
filter = {"name": "Dell"}
collection.update_one(filter, {"$set":{"price": 1800}}) # no return value

cursor = collection.find({"name": "Dell"})
for e in cursor:
    print(e)

{'_id': ObjectId('61f6a277c8144f68349798ea'), 'name': 'Dell', 'price': 1800}


In [49]:
filter = {"name": "Dell"}
result = collection.update_one(filter, {"$set":{"price": 1600}}) # no return value
print(result.modified_count)

cursor = collection.find({"name": "Dell"})
for e in cursor:
    print(e)

1
{'_id': ObjectId('61f6a277c8144f68349798ea'), 'name': 'Dell', 'price': 1600}


In [51]:
filter = {"name": "Dell"}
collection.delete_one(filter) # no return value

cursor = collection.find({"name": "Dell"})
for e in cursor:
    print(e)
    
# prints nothing
# delete_many with a filter

In [52]:
# environments which pip
# create environments and deactivate them, see docs

## unit tests

In [63]:
# setUp and TearDown is invoked before every test

#import unittest
#from creditCardValidation import *
#
#class CreditCardValidationTest(unittest.TestCase):
#    def setUp(self):
#        print('Setup')
#
#    def test_validationCard_valid(self):
#        result = validateCard(date(2023,2,2))
#        self.assertEqual('Valid', result)
#
#        
#    def test_validationCard_expired(self):
#        result = validateCard(date(2020,2,2))
#        self.assertEqual('Valid', result)
#        self.assertRaises(RuntimeError)
#        
#    def tearDown(self):
#        print("tearDown")
#        
#if __name__ == '__main__':
#    unittest.main()