# NumPy for Data Science #


In [2]:
import numpy as np
print(np)

<module 'numpy' from '/home/martin/.local/lib/python3.6/site-packages/numpy/__init__.py'>


In [2]:
a = np.array([6, 7, 8, 9])
print(a)
print(type(a))

[6 7 8 9]
<class 'numpy.ndarray'>


In [3]:
a = np.array([6, 7, 8.0, 9])
print(a)
print(type(a))

[6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [4]:
a = np.array([6, '7', 8.0, 9])
print(a)
print(type(a))

['6' '7' '8.0' '9']
<class 'numpy.ndarray'>


In [5]:
a = np.array([[1, 2], 
              [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [7]:
zeros_array = np.zeros((5, 5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
ones_array = np.ones(5)
print(type(ones_array))
print(ones_array)

<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


In [8]:
evenly_spaced = np.linspace(100, 10)
print(evenly_spaced)

[100.          98.16326531  96.32653061  94.48979592  92.65306122
  90.81632653  88.97959184  87.14285714  85.30612245  83.46938776
  81.63265306  79.79591837  77.95918367  76.12244898  74.28571429
  72.44897959  70.6122449   68.7755102   66.93877551  65.10204082
  63.26530612  61.42857143  59.59183673  57.75510204  55.91836735
  54.08163265  52.24489796  50.40816327  48.57142857  46.73469388
  44.89795918  43.06122449  41.2244898   39.3877551   37.55102041
  35.71428571  33.87755102  32.04081633  30.20408163  28.36734694
  26.53061224  24.69387755  22.85714286  21.02040816  19.18367347
  17.34693878  15.51020408  13.67346939  11.83673469  10.        ]


In [10]:
x = np.linspace(-1, 1, 11)
print(x)
y = np.sin(x)
print(y)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
[-0.84147098 -0.71735609 -0.56464247 -0.38941834 -0.19866933  0.
  0.19866933  0.38941834  0.56464247  0.71735609  0.84147098]


In [11]:
print(np.arange(15))
print(np.arange(5, 15))
print(np.arange(0, 15, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]
[ 0  4  8 12]


In [12]:
five_by_four = np.arange(20).reshape(5,4)
print(five_by_four)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [13]:
print(five_by_four.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [4]:
import pandas as pd
raw_data = pd.read_csv("/home/martin/datasets/flights.csv")
raw_data.head()

FileNotFoundError: [Errno 2] No such file or directory: '/home/martin/datasets/flights.csv'

In [ ]:
data = raw_data.to_numpy()
print(data)


In [13]:
print('data.shape: {}'.format(data.shape)

TypeError: 'tuple' object is not callable

In [17]:
print('data.size: {}'.format(data.size))

data.size: 6398744


In [18]:
print('data.ndim: {}'.format(data.ndim))

data.ndim: 2


In [19]:
dep_time = data[:, 4]
print(dep_time)
print(type(dep_time))

[515 529 540 ... 1210 1159 840]
<class 'numpy.ndarray'>


In [20]:
dep_time = data[:5, 3:6]
print(dep_time)

[[517.0 515 2.0]
 [533.0 529 4.0]
 [542.0 540 2.0]
 [544.0 545 -1.0]
 [554.0 600 -6.0]]


In [22]:
dep_delay = data[:500, 5]
print('Sum: {}'.format(dep_delay.sum()))
print('Min: {}'.format(dep_delay.min()))
print('Max: {}'.format(dep_delay.max()))
print('Ave: {}'.format(dep_delay.mean()))

Sum: 2955.0
Min: -15.0
Max: 853.0
Ave: 5.91


In [23]:
dep_delay_hours = data[:500, 5] / 60
print('Sum: {}'.format(dep_delay_hours.sum()))
print('Min: {}'.format(dep_delay_hours.min()))
print('Max: {}'.format(dep_delay_hours.max()))
print('Ave: {}'.format(dep_delay_hours.mean()))

Sum: 49.24999999999999
Min: -0.25
Max: 14.216666666666667
Ave: 0.09849999999999999


In [24]:
print('Standard Deviation: {}'.format(dep_delay_hours.std()))
print('Variance: {}'.format(dep_delay_hours.var()))

Standard Deviation: 0.7088335292734281
Variance: 0.5024449722222238


In [25]:
print(dep_delay_hours > 1)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False Fa

In [26]:
print(dep_delay_hours[dep_delay_hours > 1])

[1.6833333333333333 1.1833333333333333 14.216666666666667 2.4
 2.2333333333333334 1.6 1.1833333333333333 1.2833333333333334
 1.1666666666666667 1.9166666666666667 1.75 2.033333333333333
 1.4666666666666666 1.0666666666666667]


Numpy Documentation: https://docs.scipy.org/doc/numpy/reference/index.html